language: java

env:
  global:
    secure: HUHdHaAW6vEYMANiGKajHtlTlPlvnJM/DZ8cl8hRolNucp8rvgj/SpwfhCyzJEY+zqL++oWAqLzkkxy2lDrsUUXzPS3VZdOlMTSdTbz1W4yCGFASRiCiJSKbGw0HVdmPE5TKFDjv2QdmpEvuh3FxBM8UJBPRWRo6XU7daMb/HLmhaM4E75x0dGLue6NM6dlkMOU3k3O37xsDGRmxnfRQAu+gHZ5DckvX7Izb2cqy4BetMCf3C7SApNLZ7QdNG1PjVlnn1sBQHsINEkL4kvbWiqLSp5XfwO1809ewElqFShgl+UO/MWG0Y76n/nwLvACwdxm9+sv3OEtPb371e5xR5KpQLpoJBJP38Xpx8oltnQ4r8D6X6tDMwHD7NxIu/+0d4non5yqSBD3DT1R/ndlE0OJYLLw2+PvS/54tiFzwaA/ID4hFfyUCQVe8y0OoFbv9UaH+R1MEeVZq+jt73d3s970kZxIVI41jTnfVGm3yddwO99A8hNYJoXcW6QrMQ8VhkP47I4reUqUngLAjp5aJLyTKkEdP7BFDqo8o1lCgeW/hZSZIUG8cjq75//VzWmg2WXHdj3eP6Auh/NXWbkuRFfvPvW8yPIGp95ycP3QMgIZAo4bXiThDVa5joSSWrnGF+9Aj70PiQqtQaupk1h094NWXfvWeY++LF/9bHET0TIU=

cache:
  directories:
  - install4j7.0.7

install:
- |
  if [ ! -d install4j7.0.7/bin ];
  then
    wget https://download-keycdn.ej-technologies.com/install4j/install4j_unix_7_0_7.tar.gz
    tar -zxvf install4j_unix_7_0_7.tar.gz;
  fi

before_script:
- install4j7.0.7/bin/install4jc --license=$INSTALL4J_LICENSE

script:
- ant package-all -Dinstall4j.dir=./install4j7.0.7

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: jnxl2c9Az/DPHS8ghxPfdEH/fsgexvhEW4NHBjJILNptWSfx72+23bsUhp7SRxKgJgq3MXaB6e7hpiDJxah18yI7Og6WNBblWzkQJMeJrHvLn6vsLIAGCaUhy1gy3seZwvzCwFm/GKuZyTOUwP3TYMfda464uvc9zZLpthTJQ1Q54b8i/25eivhyuBdGm9vE4lT9jE5Xk09xrRzlOcznZMXTIDwdAtxj6UcRtxzLcT2WuIWyL+y+PVEKWy8Po6eyJT1rX0ST5y6GA25ZN3HfZXCVgDVWpNCYdcDpYKy63+pwFE397ielXh7QY3XI/0gftpSonXvrDNEsj0G8BSUNvBVcAKTzMemOpbTgqdvdpSeDeKm0+c1+07jRGcP84n5typBcrvP6nUzZRDzdxqjWHthnDpl0fHZaFSQhCrG2qYytUW2q78V5WrPA403uBwENFLalIheGPXvPB5VLGMRiv4zFIUgqpFKT5zLZ0dIL0L1bAQ0kqJ1RAvSUa74nUwgymaPwMlcD+4aB0heaPnOGvakJzhxCkv4HoHdYG7FIP9wTrJCA5aKaMFrRhlx3ZbEX4UjT3NP/ppdI0nd+pZcRcOYCbvcItaQ7DtwR53Ksq8WfVbaUsm9cqDZuaMBv/OskCUESpA0yNlXVdvF0U+hMNnKO5I4mHpGruM4rImPVhAk=
  file_glob: true
  file:
  - packages/internal/Specify*
  - packages/external/Specify*
  - packages/external/updates.xml
  skip_cleanup: true
  on:
    repo: specify/specify6
    tags: true
